all:
  hosts:
    k8s_node:
      ansible_host: 172.16.244.132
  vars:
    ansible_connection: ssh
    ansible_private_key_file: ~/.ssh/id_vagrant
    ansible_user: vagrant
    pod_cidr: 10.244.0.0/16 # flannel default cidr range
#    pod_cidr: 192.168.0.0/16 # calico default cidr range
